apiVersion: v1
kind: Service
metadata:
  name: beee-linker-api-doc
  labels:
    app: linker-api-doc
    component: microservice
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: linker-api-doc
  sessionAffinity: None
  type: ClusterIP