# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
  drafts: false
  branches:
    include:
      - develop

resources:
- repo: self

variables:
  - name: dockerRegistryServiceConnection
    value: '5b2c1a86-adaf-4fe6-84f9-536f844827fc'
  - name: imageRepository
    value: 'beee-linker-doc'
  - name: containerRegistry
    value: 'hexabase.azurecr.io'
  - name: dockerfilePath
    value: 'docker/app/Dockerfile'
  - name: tag
    value: '$(Build.BuildNumber)'
  - name: vmImageName
    value: 'ubuntu-latest'
  - group: azure-go-module-netrc

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        buildContext: $(Build.Repository.LocalPath)
        Dockerfile: $(dockerfilePath)
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        arguments: --build-arg ACCESS_TOKEN_USR=$(githubNetrcUser) --build-arg ACCESS_TOKEN_PWD=$(githubNetrcToken)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - publish: docker/k8s
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'linker-staging.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployments/linker-doc-deploy-stg.yml
                $(Pipeline.Workspace)/manifests/services/linker-doc-svc.yml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)